sudo: true
dist: trusty
language: php

php:
  - 7.2
  - 7.1
  - 5.6

env:
  global:
    - MAGENTO_DIRECTORY=${HOME}/magento
    - MAGENTO_VERSION=1.9.4.0

install:
  - git clone https://github.com/OpenMage/magento-mirror.git ${MAGENTO_DIRECTORY}
  - cd ${MAGENTO_DIRECTORY}
  - git tag -l
  - git checkout tags/${MAGENTO_VERSION}

before_script:
  - cd .

script:
  - php bin/n98-magerun.phar sys:check --root-dir=${MAGENTO_DIRECTORY}
