sudo: true
dist: trusty
language: php

php:
  - 7.1

services:
  - mysql

env:
  global:
    - MAGENTO_DIRECTORY=${HOME}/magento
    - MAGENTO_VERSION=1.9.4.0

before_install:
  - mysql -e 'CREATE DATABASE magento;'

install:
  - git clone https://github.com/OpenMage/magento-mirror.git ${MAGENTO_DIRECTORY}
  - cd ${MAGENTO_DIRECTORY}
  - git tag -l
  - git checkout tags/${MAGENTO_VERSION}
  - cd ${TRAVIS_BUILD_DIR}
  - php bin/n98-magerun.phar install --dbHost=127.0.01 --dbUser=travis --dbName=magento --dbName=magento

script:
  - php bin/n98-magerun.phar sys:check --root-dir=${MAGENTO_DIRECTORY}
