sudo: true
dist: trusty
language: php

php:
  - 7.1

services:
  - mysql

env:
  global:
    - MAGENTO_DIRECTORY=${HOME}/magento
    - MAGENTO_VERSION=1.9.4.0
    - n98=php ${TRAVIS_BUILD_DIR}/bin/n98-magerun.phar

before_install:
  - mysql -e 'CREATE DATABASE magento;'

install:
  - git clone https://github.com/OpenMage/magento-mirror.git ${MAGENTO_DIRECTORY}
  - cd ${MAGENTO_DIRECTORY}
  - git tag -l
  - git checkout tags/${MAGENTO_VERSION}
  - n98 install --dbHost=127.0.01 --dbUser=travis --dbName=magento --dbName=magento

script:
  - n98 sys:check --root-dir=${MAGENTO_DIRECTORY}
