language: php
sudo: false

php:
  - 7.1
  - 7.2

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache/files

env:
  global:
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit

before_install:
  - composer self-update

install:
  - composer install

script:
  - composer validate --strict
