sudo: true
dist: trusty
language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - mysql

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - MAGENTO_DIRECTORY=${HOME}/magento
    - MAGENTO_VERSION=1.9.4.0
    - n98="php $COMPOSER_BIN_DIR/n98-magerun --no-interaction --root-dir=${MAGENTO_DIRECTORY}"

before_install:
  - mysql -e 'CREATE DATABASE magento;'

install:
  - composer install $COMPOSER_ARGS
  - $n98 sys:check --root-dir=${MAGENTO_DIRECTORY}
  - git clone https://github.com/OpenMage/magento-mirror.git ${MAGENTO_DIRECTORY}
  - cd ${MAGENTO_DIRECTORY}
  - git tag -l
  - git checkout tags/${MAGENTO_VERSION}
  - $n98 install --dbUser=travis --dbHost=127.0.0.1 --dbName=magento --baseUrl="http://127.0.0.1" --installationFolder=${MAGENTO_DIRECTORY} --noDownload --forceUseDb
